### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mrBoie** [OPCUAUniCT/OPCUAWebPlatformUniCT#12]
Hi,

I can see that you are using "OPCFoundation.NetStandard.Opc.Ua", this package is under GPL 2.0 if you aren't a member of the OPC foundation.

http://opcfoundation.github.io/UA-.NETStandard/

Wouldn't that make your repo GPL 2.0 as well?

**Comment by OPCUAUniCT** [comment]
@mrBoie yes you are right! This was fixed. Thank you for making us aware of this.
