### ISSUE TITLE
signalR  javascript

### ISSUE THREAD

**Issue by YW767486516** [OPCUAUniCT/OPCUAWebPlatformUniCT#13]
![image](https://user-images.githubusercontent.com/45729918/64764498-c3d5c480-d574-11e9-8c0e-66226fd44311.png)
How do I request subscription data through javascript?

**Comment by msalafia** [comment]
I suggest you to follow [this](https://docs.microsoft.com/it-it/aspnet/core/signalr/javascript-client?view=aspnetcore-2.2) guide from Microsoft website.
You need a SignalR Hub (like a Broker in MQTT) and finally you can use a Javascript Client to connect to the Hub receiving messages.
