### ISSUE TITLE
Question about Main Step

### ISSUE THREAD

**Issue by tronghuybku** [OPCUAUniCT/OPCUAWebPlatformUniCT#15]
I am writing my graduation thesis with regards to your project. Would you mind letting me know the main steps in carrying out your project? Thank you for your time!

**Comment by msalafia** [comment]
What do you mean exactly? what do you want to know?

**Comment by tronghuybku** [comment]
I want to know step build your project ?? Would you mind sharing with me ?? Thank you for your time

**Comment by msalafia** [comment]
All the information needed to run the project are available in the readme. You can take advantage of a docker image too.
If you need information about the internal structure of the platform you can find all the available information on the publication provided at the bottom of the readme. Hope this can help you.

**Comment by tronghuybku** [comment]
Thank you very much !!!!
