### ISSUE TITLE
OPCUAServer in TiaPortal V16

### ISSUE THREAD

**Issue by tronghuybku** [OPCUAUniCT/OPCUAWebPlatformUniCT#18]
I want connect Platform with OPCUA Server in S7-1500 (Tia Portal). But I can't add Certificate of Platform to OPCUA Server in S7-1500

**Comment by msalafia** [comment]
I have to say that i neve had the chance to try an OPC UA Server of S7-1500 so i'm not an expert about that. 
In any case i think you have to be more specific abou the problem you faced or, at least, provide me some erreors or details about the issue. I cannot help you in this way.

**Comment by tronghuybku** [comment]
Oh thanks. But If I want to set No Security in Platform. Can you help me, please ??

**Comment by msalafia** [comment]
The Platform uses by default a secured endpoint of an OPC UA Server. This behaviour is hardcoded. If you want to change it, open the file UAClient.cs and in the function `GetSessionAsync` change:
```
endpointDescription = CoreClientUtils.SelectEndpoint(serverUrl, true, 15000);
```
with
```
endpointDescription = CoreClientUtils.SelectEndpoint(serverUrl, false, 15000);
```
I hope this solves your issue.

**Comment by tronghuybku** [comment]
Thank you very much. The Platform is running <3 <3 <3

**Comment by msalafia** [comment]
Nice, i hope you will enjoy the platform!
I'm closing this issue.
