### ISSUE TITLE
How to run web platform OPCUA

### ISSUE THREAD

**Issue by nhattran2108** [OPCUAUniCT/OPCUAWebPlatformUniCT#19]
After I Clone the project and run it .the local page appear 
![image](https://user-images.githubusercontent.com/48618235/82407223-d5bc1f80-9a92-11ea-8480-606d330a96ee.png)
How can I fix it, I just newbie to research about OPCUA webplatform.

**Comment by msalafia** [comment]
The webplatform do not include any web pages. It provides a REST api only. You can use it with any client like Postman. i hope this helps you.
