### ISSUE TITLE
Newtonsoft Json.NET Schema Component Dependency

### ISSUE THREAD

**Issue by jkancio** [OPCUAUniCT/OPCUAWebPlatformUniCT#6]
Hi,
This project depends on the Newtonsoft Json.NET Schema that is a paid Component.

Please, do you have any idea how difficult would be rewrite the code to remove this dependency?

**Comment by msalafia** [comment]
OPC UA Web Platform use two packages for managing JSON and JSON schema: Json.NET and NJsonSchema. We use only free features of the first one, because only validation are limited for free license (and we don't use them). So that, there is no need to change dependency.

Hope this could be clarifying.

**Comment by jkancio** [comment]
I'm sorry, but I've got an error:
_The free-quota limit of 10 schema generations per hour has been reached. Please visit http://www.newtonsoft.com/jsonschema to upgrade to a commercial license._

Besides that, I've seen in https://www.newtonsoft.com/jsonschema that Json.NET Schema is paid and the code has "using Newtonsoft.Json.Schema;", for instance, in ...OPCUAWebPlatformUniCT\OPCUA_Web_Platform\Models\OPCUA\UaValue.cs  (class UaValue).

Am I Wrong?

**Comment by msalafia** [comment]
This is strange because i saw that Json.NET has limitation only for JSON Schema validation (1000 per hous) and not for schema generation. 

Can you please provide the line that rise this error?

**Comment by jkancio** [comment]
Sorry, but since the time I've written to you, I could not reproduce the error anymore. 
I've been using the code and it is fine up to now.

**Comment by jkancio** [comment]
Hi, msalafia,
I've got again the error at line **238** of **DataTypeManager.cs**, as you can see bellow.

**## JSchemaException: The free-quota limit of 10 schema generations per hour has been reached. Please visit http://www.newtonsoft.com/jsonschema to upgrade to a commercial license.**

_Newtonsoft.Json.Schema.Infrastructure.Licensing.LicenseHelpers.IncrementAndCheckGenerationCount()
Newtonsoft.Json.Schema.Generation.JSchemaGenerator.Generate(Type type, bool rootSchemaNullable)
WebPlatform.OPCUALayer.DataTypeManager.SerializeFloat(VariableNode variableNode, Variant value, bool generateSchema) in DataTypeManager.cs
+
        {
            var schemaGenerator = new JSchemaGenerator();
            if (variableNode.ValueRank == -1)
            {
                var jFloatVal = new JValue(value.Value);
                **var schema = (generateSchema) ? schemaGenerator.Generate(typeof(float)) : null;**
                return new UaValue(jFloatVal, schema);
            }
            else if (variableNode.ValueRank == 1)
            {
                var arr = (Array)value.Value;
                var jArray = new JArray(arr);_

**Comment by marcostefanoscroppo** [comment]
Hi @jkancio,
try the code in the branch **issue-6**.
Please, refer to the pull request #9 for code review and let us know if this issue is solved.
Only some base DataTypes were affected by this problem. Now everything should be ok.

**Comment by jkancio** [comment]
I have tested the code since it was published and so far I have not received the error any more.
